spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/foyerdb?useSSL=false
    username: ricky
    password: 190199
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8053
application:
  config:
    chambre-url: http://localhost:9999/api/v1/chambres
    reservation-url: http://localhost:9999/api/v1/reservations
    foyer-url: http://localhost:9999/api/v1/foyers
    bloc-url: http://localhost:9999/api/v1/blocs
    etudiant-url: http://localhost:9999/api/v1/etudiants
    universite-url: http://localhost:9999/api/v1/universites
