---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloc-service-deployment
spec:
  selector:
    matchLabels:
      app: bloc-service
  replicas: 1
  template:
    metadata:
      labels:
        app: bloc-service
    spec:
      containers:
        - name: bloc-service
          image: samixouerfelli/bloc-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8050
          envFrom:
            - secretRef:
                name: blocdb-secrets
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod


---
apiVersion: v1
kind: Service
metadata:
  name: bloc-service-ssvc
spec:
  selector:
    app: bloc-service
  ports:
    - protocol: "TCP"
      port: 8050
      targetPort: 8050
  type: ClusterIP
