---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: samixouerfelli/config-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  selector:
    app: config-server
  ports:
    - protocol: "TCP"
      port: 8888
      targetPort: 8888
  type: ClusterIP
