apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: init-mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          command:
            [
              "sh", "-c",
              "until mysql -u root -p$MYSQL_ROOT_PASSWORD -h localhost -e 'GRANT ALL PRIVILEGES ON devopsprojectDB.* TO \"root\"@\"%\" IDENTIFIED BY \"root\"; FLUSH PRIVILEGES;'; do echo 'Waiting for MySQL to be ready...'; sleep 10; done"
            ]
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: "TCP"
      port: 3306
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsproject-deployment
spec:
  selector:
    matchLabels:
      app: devopsproject
  replicas: 2
  template:
    metadata:
      labels:
        app: devopsproject
    spec:
      containers:
        - name: devopsproject
          image: samixouerfelli/devopsproject:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devopsproject-ssvc
spec:
  selector:
    app: devopsproject
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
