---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mariadb:10.4.32
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: foyer
            - name: MYSQL_DATABASE
              value: foyerdb
            - name: MYSQL_USER
              value: foyer
            - name: MYSQL_PASSWORD
              value: foyer

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsproject-deployment
spec:
  selector:
    matchLabels:
      app: devopsproject
  replicas: 1
  template:
    metadata:
      labels:
        app: devopsproject
    spec:
      containers:
        - name: devopsproject
          image: samixouerfelli/devopsproject:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://db-service:3306/foyerdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&characterEncoding=utf-8
            - name: SPRING_DATASOURCE_USERNAME
              value: foyer
            - name: SPRING_DATASOURCE_PASSWORD
              value: foyer
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
---
apiVersion: v1
kind: Service
metadata:
  name: devopsproject-ssvc
spec:
  selector:
    app: devopsproject
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
