apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsproject-deployment
spec:
  selector:
    matchLabels:
      app: devopsproject
  replicas: 2
  template:
    metadata:
      labels:
        app: devopsproject
    spec:
      containers:
        - name: devopsproject
          image: samixouerfelli/devopsproject:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: devopsproject-ssvc
spec:
  selector:
    app: devopsproject
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer