apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
spec:
  selector:
    matchLabels:
      app: devops
  replicas: 2
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: devops
          image: cyrine105/devops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"   # Set a memory limit
              ephemeral-storage: "1Gi"  # Set a storage limit
            requests:
              memory: "256Mi"
              ephemeral-storage: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-ssvc
spec:
  selector:
    app: devops
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
