apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
spec:
  selector:
    matchLabels:
      app: devops
  replicas: 2 
  template:
    metadata:
      labels:
        app: devops
    spec:
      automountServiceAccountToken: false
      containers:
        - name: devops
          image: louaykh1/devops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"

---

apiVersion: v1 
kind: Service 
metadata: 
  name: devops-ssvc
spec:
  selector:
    app: devops
  ports:
    - protocol: "TCP"
      port: 8080 
      targetPort: 8080 
  type: LoadBalancer
