apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mariadb:10.4.32
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ricky
            - name: MYSQL_DATABASE
              value: devopsdb
            - name: MYSQL_USER
              value: ricky
            - name: MYSQL_PASSWORD
              value: ricky

          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsproject-deployment
spec:
  selector:
    matchLabels:
      app: devopsproject
  replicas: 2
  template:
    metadata:
      labels:
        app: devopsproject
    spec:
      containers:
        - name: devopsproject
          image: samixouerfelli/devopsproject:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: DB_SERVER
            value: mysql-service
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: devopsdb
          - name: DB_USERNAME
            value: ricky
          - name: DB_PASSWORD
            value: ricky
---
apiVersion: v1
kind: Service
metadata:
  name: devopsproject-ssvc
spec:
  selector:
    app: devopsproject
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
