services:
  universite:
    container_name: universitedb
    image: postgres
    environment:
      POSTGRES_USER: ricky
      POSTGRES_PASSWORD: 190199
      POSTGRES_DB: universitdb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres6:/var/lib/postgresql/data
    ports:
      - 5437:5432
    restart: unless-stopped

volumes:
  postgres6: