version: '3.8'

services:
  discovery-server:
    image: samixouerfelli/discovery-server:latest
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: local
      CONFIG_SERVER_URL: http://host.docker.internal:8888
    depends_on:
      - config-server
