services:
  chambre:
    container_name: ms-reservation-db
    image: postgres
    environment:
      POSTGRES_USER: ricky
      POSTGRES_PASSWORD: 190199
      POSTGRES_DB: reservationdb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres4:/var/lib/postgresql/data
    ports:
      - 5436:5432
    restart: unless-stopped

volumes:
  postgres4: