---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etudiant-service-deployment
spec:
  selector:
    matchLabels:
      app: etudiant-service
  replicas: 1
  template:
    metadata:
      labels:
        app: etudiant-service
    spec:
      containers:
        - name: etudiant-service
          image: samixouerfelli/etudiant-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8052
          envFrom:
            - secretRef:
                name: etudiantdb-secrets
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: etudiant-service-ssvc
spec:
  selector:
    app: etudiant-service
  ports:
    - protocol: "TCP"
      port: 8052
      targetPort: 8052
  type: ClusterIP