apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: myapp
  labels:
    app: myapp
spec:
  replicas: 1  # Starting with 1 replica for testing
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: lookabj/myapp:latest
        imagePullPolicy: IfNotPresent  # Important for Kind
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"  # Reduced for Kind
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      # No readiness/liveness probes for initial testing