apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: myapp
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2  # Increased to 2 replicas like in the example
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: lookabj/myapp:latest
          imagePullPolicy: Always  # Changed to Always like in the example
          ports:
            - containerPort: 8080