apiVersion: v1
kind: Namespace
metadata:
  name: myapp

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: myapp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-role-binding
  namespace: myapp
subjects:
- kind: ServiceAccount
  name: default
  namespace: myapp
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io