apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-app-monitor
  namespace: myapp
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: myapp
  namespaceSelector:
    matchNames:
      - myapp
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s