
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: universite-service-deployment
spec:
  selector:
    matchLabels:
      app: universite-service
  replicas: 1
  template:
    metadata:
      labels:
        app: universite-service
    spec:
      containers:
        - name: universite-service
          image: samixouerfelli/universite-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8055
          envFrom:
            - secretRef:
                name: universitedb-secrets
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: universite-service-ssvc
spec:
  selector:
    app: universite-service
  ports:
    - protocol: "TCP"
      port: 8055
      targetPort: 8055
  type: ClusterIP