server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
       server:
        git:
         uri: https://github.com/samiouerfelli/DEVOPS_PROJECT_G2.git
         default-label: config-server
         clone-on-start: true
         searchPaths: src/main/resources/prod
         username: ${git.username}
         password: ${git.password}


