server:
  port: 8888
spring:
  profiles:
    active: k8s
  application:
    name: config-server
  cloud:
    config:
       server:
        git:
         uri: https://github.com/samiouerfelli/DEVOPS_PROJECT_G2.git
         default-label: config-server
         clone-on-start: true
         search-paths: config-k8s
