spring:
  datasource:
    url: jdbc:postgresql://db-service-blocdb:5432/blocdb?useSSL=false
    username: ricky
    password: 190199
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: k8s
server:
  port: 8050

