spring:
  datasource:
    url: jdbc:postgresql://db-service-chambredb:5433/chambredb?useSSL=false
    username: ricky
    password: 190199
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      uri: http://config-server:8888  # Address of the Config Server service in Kubernetes
      fail-fast: true


server:
  port: 8051

