spring:
  datasource:
   # url: jdbc:postgresql://db-postgresql-nyc3-72282-do-user-17776513-0.m.db.ondigitalocean.com:25060/blocdb?useSSL=require
   # username: ricky
  #  password: AVNS_uIQzaMHDaubeDTEroHy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: bloc-service
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}