spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/foyerdb?useSSL=false
    username: ricky
    password: 190199
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8053
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
application:
  config:
    bloc-url: http://localhost:8099/api/v1/bloc
    universite-url: http://localhost:8099/api/v1/universite
