spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/foyerdb?useSSL=false
    username: ricky
    password: 190199
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8053
eureka:
  client:
    enabled: false


